project_name: jsc
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: jsc
    ldflags: -s -w -X main.version={{.Version}} -X main.revision={{.ShortCommit}} -X main.date={{.Date}}
archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: x86_64
    files:
      - LICENSE
      - CREDITS
release:
  prerelease: auto
brews:
  - tap:
      owner: michimani
      name: homebrew-jsc
    folder: Formula
    homepage: 'https://github.com/michimani/jsc'
    description: 'A tool that joins multiple slack channels to display posts in chronological order.'
    license: 'MIT'